/*******************************************************************************/
/**********************    Name	: Ahmed Khaled ****************************/
/**********************    Date	: 27/8/2020         ****************************/
/**********************    SWC	: DIO      			****************************/
/********************    Version: 1.0   			****************************/
/*******************************************************************************/
#ifndef DIO_CONFIG_H
#define DIO_CONFIG_H

/* Intial Directions For All Pins */
/* Options : DIO_u8_INTIAL_OUTPUT
			 DIO_u8_INTIAL_INPUT	*/
/* PORTA */
#define DIO_u8_PA0_INTIAL_DIRECTION		DIO_u8_INTIAL_INPUT //LM35
#define DIO_u8_PA1_INTIAL_DIRECTION		DIO_u8_INTIAL_INPUT	//LDR
#define DIO_u8_PA2_INTIAL_DIRECTION		DIO_u8_INTIAL_INPUT //Empty
#define DIO_u8_PA3_INTIAL_DIRECTION		DIO_u8_INTIAL_INPUT //Empty
#define DIO_u8_PA4_INTIAL_DIRECTION		DIO_u8_INTIAL_OUTPUT //Empty
#define DIO_u8_PA5_INTIAL_DIRECTION		DIO_u8_INTIAL_OUTPUT //Buzzer
#define DIO_u8_PA6_INTIAL_DIRECTION		DIO_u8_INTIAL_OUTPUT //Red Led
#define DIO_u8_PA7_INTIAL_DIRECTION		DIO_u8_INTIAL_OUTPUT //Green Led

/* PORTB */
#define DIO_u8_PB0_INTIAL_DIRECTION		 DIO_u8_INTIAL_OUTPUT  //KPD
#define DIO_u8_PB1_INTIAL_DIRECTION		 DIO_u8_INTIAL_OUTPUT  //KPD
#define DIO_u8_PB2_INTIAL_DIRECTION		 DIO_u8_INTIAL_OUTPUT  //KPD
#define DIO_u8_PB3_INTIAL_DIRECTION		 DIO_u8_INTIAL_OUTPUT  //KPD
#define DIO_u8_PB4_INTIAL_DIRECTION		 DIO_u8_INTIAL_INPUT   //KPD
#define DIO_u8_PB5_INTIAL_DIRECTION		 DIO_u8_INTIAL_INPUT   //KPD
#define DIO_u8_PB6_INTIAL_DIRECTION		 DIO_u8_INTIAL_INPUT   //KPD
#define DIO_u8_PB7_INTIAL_DIRECTION		 DIO_u8_INTIAL_INPUT   //KPD

/* PORTC */
#define DIO_u8_PC0_INTIAL_DIRECTION		 DIO_u8_INTIAL_OUTPUT  //LCD
#define DIO_u8_PC1_INTIAL_DIRECTION		 DIO_u8_INTIAL_OUTPUT  //LCD
#define DIO_u8_PC2_INTIAL_DIRECTION		 DIO_u8_INTIAL_OUTPUT  //LCD
#define DIO_u8_PC3_INTIAL_DIRECTION		 DIO_u8_INTIAL_OUTPUT  //LCD
#define DIO_u8_PC4_INTIAL_DIRECTION		 DIO_u8_INTIAL_OUTPUT  //LCD
#define DIO_u8_PC5_INTIAL_DIRECTION		 DIO_u8_INTIAL_OUTPUT  //LCD
#define DIO_u8_PC6_INTIAL_DIRECTION		 DIO_u8_INTIAL_OUTPUT  //LCD
#define DIO_u8_PC7_INTIAL_DIRECTION		 DIO_u8_INTIAL_OUTPUT  //LCD

/* PORTD */
#define DIO_u8_PD0_INTIAL_DIRECTION		 DIO_u8_INTIAL_OUTPUT	//RS
#define DIO_u8_PD1_INTIAL_DIRECTION		 DIO_u8_INTIAL_OUTPUT	//RW
#define DIO_u8_PD2_INTIAL_DIRECTION		 DIO_u8_INTIAL_INPUT	//Gas Sensor
#define DIO_u8_PD3_INTIAL_DIRECTION		 DIO_u8_INTIAL_INPUT	//Flame Sensor
#define DIO_u8_PD4_INTIAL_DIRECTION		 DIO_u8_INTIAL_OUTPUT 	//Empty
#define DIO_u8_PD5_INTIAL_DIRECTION		 DIO_u8_INTIAL_OUTPUT	//Servo Motor
#define DIO_u8_PD6_INTIAL_DIRECTION		 DIO_u8_INTIAL_OUTPUT  //Empty
#define DIO_u8_PD7_INTIAL_DIRECTION		 DIO_u8_INTIAL_OUTPUT	//E -> LCD


/* Intial Values For All Pins */
/* Options :DIO_u8_OUTPUT_LOW
			DIO_u8_OUTPUT_HIGH
			DIO_u8_INPUT_FLOATING
			DIO_u8_INPUT_PULLUP		*/
/* PORTA */
#define DIO_u8_PA0_INTIAL_VALUE		 DIO_u8_INPUT_FLOATING
#define DIO_u8_PA1_INTIAL_VALUE		 DIO_u8_INPUT_FLOATING
#define DIO_u8_PA2_INTIAL_VALUE		 DIO_u8_OUTPUT_HIGH
#define DIO_u8_PA3_INTIAL_VALUE		 DIO_u8_OUTPUT_HIGH
#define DIO_u8_PA4_INTIAL_VALUE		 DIO_u8_OUTPUT_LOW
#define DIO_u8_PA5_INTIAL_VALUE		 DIO_u8_OUTPUT_LOW
#define DIO_u8_PA6_INTIAL_VALUE		 DIO_u8_OUTPUT_LOW
#define DIO_u8_PA7_INTIAL_VALUE		 DIO_u8_OUTPUT_LOW

/* PORTB */
#define DIO_u8_PB0_INTIAL_VALUE		 DIO_u8_OUTPUT_HIGH
#define DIO_u8_PB1_INTIAL_VALUE		 DIO_u8_OUTPUT_HIGH
#define DIO_u8_PB2_INTIAL_VALUE		 DIO_u8_OUTPUT_HIGH
#define DIO_u8_PB3_INTIAL_VALUE		 DIO_u8_OUTPUT_HIGH
#define DIO_u8_PB4_INTIAL_VALUE		 DIO_u8_INPUT_PULLUP
#define DIO_u8_PB5_INTIAL_VALUE		 DIO_u8_INPUT_PULLUP
#define DIO_u8_PB6_INTIAL_VALUE		 DIO_u8_INPUT_PULLUP
#define DIO_u8_PB7_INTIAL_VALUE		 DIO_u8_INPUT_PULLUP

/* PORTC */
#define DIO_u8_PC0_INTIAL_VALUE		 DIO_u8_OUTPUT_LOW
#define DIO_u8_PC1_INTIAL_VALUE		 DIO_u8_OUTPUT_LOW
#define DIO_u8_PC2_INTIAL_VALUE		 DIO_u8_OUTPUT_LOW
#define DIO_u8_PC3_INTIAL_VALUE		 DIO_u8_OUTPUT_LOW
#define DIO_u8_PC4_INTIAL_VALUE		 DIO_u8_OUTPUT_LOW
#define DIO_u8_PC5_INTIAL_VALUE		 DIO_u8_OUTPUT_LOW
#define DIO_u8_PC6_INTIAL_VALUE		 DIO_u8_OUTPUT_LOW
#define DIO_u8_PC7_INTIAL_VALUE		 DIO_u8_OUTPUT_LOW

/* PORTD */
#define DIO_u8_PD0_INTIAL_VALUE		 DIO_u8_OUTPUT_LOW
#define DIO_u8_PD1_INTIAL_VALUE		 DIO_u8_OUTPUT_LOW
#define DIO_u8_PD2_INTIAL_VALUE		 DIO_u8_INPUT_PULLUP
#define DIO_u8_PD3_INTIAL_VALUE		 DIO_u8_INPUT_PULLUP
#define DIO_u8_PD4_INTIAL_VALUE		 DIO_u8_OUTPUT_LOW
#define DIO_u8_PD5_INTIAL_VALUE		 DIO_u8_OUTPUT_LOW
#define DIO_u8_PD6_INTIAL_VALUE		 DIO_u8_OUTPUT_LOW
#define DIO_u8_PD7_INTIAL_VALUE		 DIO_u8_OUTPUT_LOW

#endif
